---
all:
  vars:
    ansible_user: ubuntu
    ansible_ssh_private_key_file: /home/ubuntu/.ssh/id_ed25519
    ansible_python_interpreter: /usr/bin/python3
    ansible_port: 22
  children:
    ubuntu:
      hosts:
        test:
          ansible_host: 192.168.3.3
    